- name: My fantastic playbook!
  hosts: all
  pre_tasks:
    - name: "Group by stage in pre_tasks!"
      group_by:
        key: "stage_{{stage}}"
      changed_when: false
  tasks:
    - name: "Get uptime"
      command: uptime
      register: uptime
      changed_when: no
    - name: "This is the value in tasks!"
      debug:
        msg: "{{my_stage_specific_thing}} ({{inventory_hostname}}, {{uptime.stdout}} {{inventory_file}} {{inventory_dir}})"
