- name: My fantastic playbook!
  hosts: all
  tasks:
    - name: Group by stage!
      group_by:
        key: "stage_{{stage}}"
    - name: "This is the value"
      debug:
        msg: "{{my_stage_specific_thing}} ({{inventory_hostname}})"